### ISSUE TITLE
Support for stable rust?

### ISSUE THREAD

**Issue by raskchanky** [alecmocatta/palaver#9]
Hi,

Are there any plans for this crate to support stable rust?  Right now, `valgrind_request`, which is a dep, uses nightly only features.

**Comment by alecmocatta** [comment]
Thanks @raskchanky, I just made a couple changes to support stable:

I've just gated `valgrind_request` behind a "nightly" feature flag. So it can now be excluded with:
```toml
palaver = { version = "0.2", default-features = false }
```

I also switched [`#![feature(try_from)]`](https://github.com/rust-lang/rust/issues/33417) to use the [`try_from`](https://crates.io/crates/try_from) crate. I'll revert this when `#![feature(try_from)]` is stabilised.

**Comment by raskchanky** [comment]
Awesome, thank you!
